services:
  image: "ghcr.io/technulgy-lgnu/technulgy-website:${GIT_COMMIT_HASH:-latest}"
  deploy:
    placement:
      constrains:
        - node.role == worker
    replicas: 2
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`technulgy.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=cfACME"